---
# tasks file for Buck
- name: Install packages
  ansible.builtin.apt:
    state: present
    force_apt_get: true
    pkg:
      - curl
      - build-essential
  become: true

- name: Retrive rustup
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: ./rustup.sh
    mode: "0700"

- name: Install rustup # noqa no-changed-when
  ansible.builtin.command: ./rustup.sh -q -y

- name: Install nightly-2023-03-07
  ansible.builtin.command: ./.cargo/bin/rustup install nightly-2023-03-07

- name: Make bin directory
  ansible.builtin.file:
    path: /home/ubuntu/bin
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0755"

- name: Copy over buck2 install script
  ansible.builtin.copy:
    src: buck.sh.j2
    dest: bin/buck.sh
    owner: ubuntu
    group: ubuntu
    mode: '0755'
